spring.application.name=questionbank
spring.datasource.url=jdbc:mysql://localhost:3306/question_bank
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false
